version: '3.8'

services:
  postgres:
    container_name: reports-postgres
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env
    expose:
      - 5432

  django:
    container_name: reports-django
    build: ./backend
    command: gunicorn main.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/usr/src/backend
      - ./static:/usr/src/static
      - media:/usr/src/media
      - logs:/usr/src/logs
    expose:
      - 8000
    env_file: .env
    depends_on:
      - postgres

  vue:
    container_name: reports-vue
    build: ./frontend
    volumes:
      - frontend:/usr/src/frontend
    env_file: .env
    depends_on:
      - django

  nginx:
    container_name: reports-nginx
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - static:/usr/src/static
      - media:/usr/src/media
      - frontend:/usr/src/frontend
    depends_on:
      - django
      - vue

volumes:
  postgres_data:
  static:
  media:
  logs:
  frontend:
